"""allow_null_video_in_projects

Revision ID: cc190b9e02b5
Revises: a4df3d5bc342
Create Date: 2026-04-28 11:19:01.438120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc190b9e02b5'
down_revision: Union[str, Sequence[str], None] = 'a4df3d5bc342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'video_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('projects', 'video_meta',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'video_meta',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('projects', 'video_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
